config/routes.rb
Rails.application.routes.draw do

  
  root            'static_pages#home'
  get 'help' =>   'static_pages#help'
  get 'about' =>  'static_pages#about'
  get 'teams' =>  'static_pages#teams'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  #VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def help
  end
  
  def about
  end
  
  def teams
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
  
  def show
    @user = User.find_by(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # Return full title on page-by-page basis
  def full_title(page_title = '')
    base_title = "WiscoHockey"
    
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Northeast Wisconsin Hockey
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "The Blog", '#'%></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "NEWHockey", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Teams", teams_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <li><%= link_to "Log In", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>All about NEWHockey.com</h1>
<p>Some good information here</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact me!</h1>
<p>Here's my information:</p>
<p><strong>Geoff Wild</strong></p>
<p><strong>Email</strong> put email here</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Need some help?</h1>
<p>Future help information</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
    <h1>Northeast Wisconsin Hockey</h1>
    <p>Your home for hockey in northeast Wisconsin hockey</p>
    
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary"%>
</div>

app/views/static_pages/teams.html.erb
<% provide(:title, "Teams") %>
<h1>Teams</h1>
<p>Here are some of the teams in the area</p>

app/views/users/new.html.erb
<% provide(:title, "Sign Up") %>
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.email %>